### ISSUE TITLE
Is there a way to publish snap for multi-archs at once?

### ISSUE THREAD

**Issue by twang2218** [canonical/action-publish#22]
I'm trying to create a snap build/publish for multiple architectures, e.g. `amd64`, `ia32` and `arm64`, I didn't find a way to publish the snaps of multiple archs to the snap store at once. I have to call this action multiple times for now. Is there anything I'm missing?

**Comment by willcharlton** [comment]
Same here. Do we really have to have two separate blocks of YAML to do multiarch support in the Store?

**Comment by prodrigestivill** [comment]
It can be configured to build and publish using a github matrix:

```yaml

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
    steps:
      - uses: actions/checkout@v3

      - uses: snapcore/action-build@v1
        id: build
        with:
          snapcraft-args: --build-for=${{ matrix.arch }}
  
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
```

May be a similar example can be added in either this action or the build one.
