### ISSUE TITLE
Getting Error: login_data is empty

### ISSUE THREAD

**Issue by vbmade2000** [canonical/action-publish#29]
Hi there,

first of all thanks for creating this functionality. Unfortunately, while trying to publish a snap I am getting `Error: login_data is empty`. 
Here is the workflow.yml.
```

name: Snap

on:
  push:
    tags:
      - "*"

jobs:
  create-snap:
    name: Create snap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
        id: build-snap

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build-snap.outputs.snap }}
          release: edge

```        
I have created a secret in repo called STORE_LOGIN with exported snapcraft credentials using command `snapcraft export-login --snaps=mqttwrk --acls package_access,package_push,package_update,package_release /tmp/expodted.txt`.

One observation is the output from command `snapcraft export-login...`  doesn't start with `[login.ubuntu.com]` as mentioned in https://github.com/snapcore/action-publish/blob/master/README.md. I don't know if I am doing something wrong here or output is changed in latest version.

Please help me to figure out solution.
